name: Package PMM Mod Importer

on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    # Added permissions to allow the workflow to create a release
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Prepare Folder Structure
        run: |
          mkdir PMM_Mod_Importer
          cp LICENSE README.md content.js icon128.png manifest.json popup.html popup.js PMM_Mod_Importer/

      - name: Create Zip Archive
        run: |
          zip -r PMM_Mod_Importer.zip PMM_Mod_Importer/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: PMM_Mod_Importer.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}